NumPy Arrays

In [2]:
import numpy as np

 Keep in mind that numpy converts the list into the array. As you can see below how the numpy converts the list into the numpy Arrays.


In [3]:
arr=np.array([1,2,3,4,5]);
arr


array([1, 2, 3, 4, 5])

As we can see Below the different data types can be present in the lists. As we deipsly lists it will show differet data types.But as convert this list into the Numpy Arrays that will converted into the univcodig strings

In [5]:
b=[2,3,4,5,4.5, 'zain'];
b


[2, 3, 4, 5, 4.5, 'zain']

In [6]:
np.array(b)

array(['2', '3', '4', '5', '4.5', 'zain'], dtype='<U32')

Above you can see that if we give differet datatypes in the list . If covert that list ito the numpy array that list will covert all data types into unicdoing 32 means strings . All ddata types is converted into the U32 strings as you ca see above.

In [14]:
l=[[2,3,4],[5,6,7],[8,9,10]]
l


[[2, 3, 4], [5, 6, 7], [8, 9, 10]]

Here we can see that when the lists are coverted into the numpy arrays then tehy are coverted intot he multi dimentionals arrays.

In [16]:
m=np.array(l);
m


array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

**Array Generation Functions**
We can generate the numpy array using the arange function.
np.arange(1,10,2). Here 1 will starting and 10 will be ending and 2 will show the gap between the 2. You can see the example below.
np.zeros(0) will be used for creating the Zeros.



In [17]:
arr=np.arange(1,11,2);
arr

array([1, 3, 5, 7, 9])

In [20]:
arr =np.array([[5,6,7],[9,8,2],[7,5,6]])
arr

array([[5, 6, 7],
       [9, 8, 2],
       [7, 5, 6]])

In [24]:
arr2=np.zeros(6);
arr2

array([0., 0., 0., 0., 0., 0.])

It will give us 2-D Arrray with zeros;

In [23]:
arr3=np.zeros((3,3));
arr3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**Use of LinSpace**
Linpace will  return the evenly space numbers with specified Interval
arr4=np.linspace(1,5,2);
It will give the 2 elements between the 1 and 5
array([1., 5.])


In [29]:
arr4=np.linspace(1,5);
arr4



array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [27]:
arr4=np.linspace(1,5,2);
arr4

array([1., 5.])

**Radom Generationn Function**


In [30]:
a=np.random.rand(10);
a

array([0.41980222, 0.09566372, 0.88926646, 0.14944718, 0.86420404,
       0.94829359, 0.18826355, 0.31067632, 0.58153583, 0.16110165])

But this gives the normalization values Now I want the standardization Values.

*   For standardization you will use  the  *np.random.randn();*
*   for Normalizationn Values we will use the   np.raddom.rand();

*   For generating the random Integer *np.random.randint(10);*
*   For genrating the randointtergs betweenn the numbers or specific np.random.randint(10,2)






In [31]:
a=np.random.randn(10);
a

array([-0.02542754,  1.05934961, -0.02125288, -1.35125919,  0.51046774,
       -0.69324051, -0.80225134,  1.54773998,  0.68726383, -2.07306428])

In [33]:
c=np.random.randint(10);
c

4

In [ ]:
c=np.random.randint(10,2);
c

**Array Attributes and Array Methods**


In [34]:
arr5=np.array([1,2,4,5]);
arr5



array([1, 2, 4, 5])

**Array Attribute**

*   arr.shape is attribute so keep in  mind  that done put brackets along the **arr.shape()**
*   arr.size is attribute so keep in  mind  that done put brackets along the **arr.size()**
see the example below.

In [35]:
arr5.shape

(4,)

In [36]:
arr5.size

4

**Array Methods**


*.  arr.min(). Method for calculating the sum of array.
*   arr.sum(). this is the by default function of the python


*    np.sum(arr,axis) In this sum is the methods provided by the nummpyy
*   List item





In [ ]:
arr.sum()

np.int64(55)

In [ ]:
arr.min()

np.int64(2)

In [ ]:
arr.max()

np.int64(9)

Nnumpy Methods

*   List item
*   List item


But numpy also have the inbuilt sum Method

In [37]:
np.sum(arr,axis=0)

array([21, 19, 15])

In [ ]:
avg=arr.mean()
avg

In [ ]:
stnd=arr.std()
stnd

** Array Resizing and Reshaping **

In [41]:
arr=np.arange(1,31);
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [42]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

**Array Slicing and Array Indexing**


*   Indexing and Slicing of Vectors
*   Numpy indexing ad slicing of Matrix

*   Boolean Indexing





**Array Indexing**



In [44]:
arr=np.arange(11,20)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [45]:
arr[2]

np.int64(13)

Here we will perfom the Array Slicing

*   first we will aslide from start adn endigng index
*   Second We will  alsoo see that how to give the Intervals. .



In [56]:
arr=np.arange(21,30)
arr

array([21, 22, 23, 24, 25, 26, 27, 28, 29])

In [57]:
arr_slice = arr[3:6]
arr_slice

array([24, 25, 26])

If starting Value is not given. It will automatically starts fromm the zero index

In [58]:
arr_slice = arr[:6]
arr_slice

array([21, 22, 23, 24, 25, 26])

In [ ]:
arr_slice = arr[3:]
arr_slice


It will show the elemments but skipping the intervals of 2

In [60]:
arr_slice = arr[3::2]
arr_slice

array([24, 26, 28])

In [49]:
arr_slice = arr[3:6:2]
arr_slice

array([24, 26])

**Array Slicing in 2-D Array (Or Matrix) **
*   Now We will seee how the slicing is done in the 2-d Array.



In [66]:
arr=np.arange(1,31).reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

*   We can see if we give the single element then it will give the Row from that particular matrix




In [67]:
arr_slice1=arr[2]
arr_slice1

array([13, 14, 15, 16, 17, 18])

In [75]:
arr_slice =arr[0:3,1:3]
arr_slice

array([[ 2,  3],
       [ 8,  9],
       [14, 15]])

Task: We have to display the 17,18, 23, 24 29, 30


In [76]:
arr_slice =arr[2:5,4:6]
arr_slice

array([[17, 18],
       [23, 24],
       [29, 30]])

In [70]:
arr_slice=arr[1]
arr_slice

array([ 7,  8,  9, 10, 11, 12])


*   ***arr[2,3] ***
*   First Element will show the row

*   Second elemment will show the column.





In [69]:
arr_slice=arr[2,3]
arr_slice

np.int64(16)

In [72]:
arr_slice= arr[:,2]
arr_slice

array([ 3,  9, 15, 21, 27])

In [ ]:
arr_slice=arr[3,4]
arr_slice

np.int64(23)

In [ ]:
arr_slice=arr[2:,3:]
arr_slice

array([[16, 17, 18],
       [22, 23, 24],
       [28, 29, 30]])

In [ ]:
arr_slice1=arr[2:4,3:5]
arr_slice1

**Boolean Indexing**

In [83]:
arr =np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
bool_index= arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

** Note **

*   If you pass the *bool_index*  array in the list then it will only show the elements with the true list.



In [85]:
arr=arr[bool_index]
arr

array([ 2,  4,  6,  8, 10])

**Array Functions **


*   Arithmatic operationns
*   Broadcasting Operations


*   Deep and Shallow Copy
*   Matrix Operation

*   Advance Array Manipulation
*   Stacking Array

*   Spliting Array
*   









In [86]:
import numpy as np

In [88]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr1
arr2

array([ 6,  7,  8,  9, 10])

Now we will peform the Simple Array Fucntions..

In [89]:
arr1+arr2

array([ 7,  9, 11, 13, 15])

In [90]:
arr1-arr2

array([-5, -5, -5, -5, -5])

In [91]:
arr1*arr2

array([ 6, 14, 24, 36, 50])

In [92]:
arr2/arr1

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

**Array BroadCasting**
Here We Will seee hwo the broadCAsting Works

In [ ]:
l=[10,20,30,40]
arr=np.array(l);
arr

array([10, 20, 30, 40])

In [ ]:
arr+10

array([20, 30, 40, 50])

In [ ]:
arr=np.arange(1,26).reshape(5,5);
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
arr2=arr+10

In [ ]:
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

**Deep Copy and Shallow Copy**

First We will see the Deep Copy

In [93]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
b=a
b


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Now we will see the id any changes occur in a then bw ill be automaiicallly updated

In [98]:
slice=a[:5]
slice=slice*10
slice

array([10, 20, 30, 40, 50])

In [99]:
b[1]=99
b

array([ 1, 99,  3,  4,  5,  6,  7,  8,  9])

In [100]:
a

array([ 1, 99,  3,  4,  5,  6,  7,  8,  9])

Here you can see if we change the then a will automaticaly Changed.
so this is deep copy concept

**Shallow Copy**
In shallow copy if some array si sliced and channges are made in sliced array then only the sliced array chages the origiional array remains sam .

Above  we have implemented the concept of  the Shallow Cop.

Now we will see the shallow copy concept

In [114]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
a
c=a.copy()
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
c[0]=99
print(c)

[99  2  3  4  5  6  7  8  9]


You can see below that a remains UnChaged.

In [125]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**Matrix Operations **

In [142]:
A=np.array([[1,2,3],[4,5,6]])
B= np.array([[7,8,9],[23,12,10]])

In [139]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [140]:
B

array([[ 7,  8,  9],
       [23, 12, 10]])

In [141]:
A*B

array([[ 7, 16, 27],
       [92, 60, 60]])

**Notes**
As you can see above the multiplication of the mtarices have beenn dout origionally the multiplication is nnot odne in done in this way in origional way.

*   For applyig np.dot() keep in mind that number of columns of first Matrix is equal to the numeber of rows of second matrix  
*   For applying the traspose **  A.T  ** of the matrix, both matrix must be the square matrixes.



In [144]:
np.dot(A,B)



ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [145]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

**Advance Array Manipulation**


*   Stacking Array (Vertical Stack, Horizontal Stack,Simple Stack)
*   Splittig Array



In [146]:
A=np.array([1,2,3,7,9])
B=np.array([7,8,9,8,9])

In [147]:
np.vstack((A,B))

array([[1, 2, 3, 7, 9],
       [7, 8, 9, 8, 9]])

In [148]:
np.hstack((A,B))

array([1, 2, 3, 7, 9, 7, 8, 9, 8, 9])

In [150]:
np.column_stack((a,b))

array([[ 1,  1],
       [ 2, 99],
       [ 3,  3],
       [ 4,  4],
       [ 5,  5],
       [ 6,  6],
       [ 7,  7],
       [ 8,  8],
       [ 9,  9]])

**Splitting Arrays **

In [166]:
arr=np.arange(0,36).reshape(6,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [167]:
np.hsplit(arr,2)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20],
        [24, 25, 26],
        [30, 31, 32]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23],
        [27, 28, 29],
        [33, 34, 35]])]